directories:
  output: release
  buildResources: build
appId: com.mundocode.twitchsorteo
productName: Twitch Sorteos
files:
  - filter:
      - dist/**
      - dist-electron/**
      - package.json
publish:
  - provider: github
    owner: Mund0Code
    repo: Twitch-Sorteos
win:
  target: nsis
mac:
  target: dmg
electronVersion: 30.5.1
